function get_table_html_mapping() {
  var layout_to_html = [
    ['key_one', "true", '!', 0x21],
    ['key_apostrophe', "true", '"', 0x22],
    ['key_three', "true", '#', 0x23],
    ['key_four', "true", '$', 0x24],
    ['key_five', "true", '%', 0x25],
    ['key_seven', "true", '&', 0x26],
    ['key_apostrophe', "false", '\'', 0x27],
    ['key_nine', "true", '(', 0x28],
    ['key_zero', "true", ')', 0x29],
    ['key_eight', "true", '*', 0x2A],
    ['key_equals', "true", '+', 0x2B],
    ['key_comma', "false", ',', 0x2C],
    ['key_hyphen', "false", '-', 0x2D],
    ['key_period', "false", '.', 0x2E],
    ['key_forwardslash', "false", '/', 0x2F],
    ['key_zero', "false", '0', 0x30],
    ['key_one', "false", '1', 0x31],
    ['key_two', "false", '2', 0x32],
    ['key_three', "false", '3',0x33],
    ['key_four', "false", '4', 0x34],
    ['key_five', "false", '5', 0x35],
    ['key_six', "false", '6', 0x36],
    ['key_seven', "false", '7',0x37],
    ['key_eight', "false", '8',0x38],
    ['key_nine', "false", '9', 0x39],
    ['key_semicolon', "true", ':', 0x3A],
    ['key_semicolon', "false", ';', 0x3B],
    ['key_comma', "true", '<', 0x3C],
    ['key_equals', "false", '=', 0x3D],
    ['key_period', "true", '>', 0x3E],
    ['key_forwardslash', "true", '?',0x3F],
    ['key_two', "true", '@', 0x40],
    ['key_a', "true", 'A', 0x41],
    ['key_b', "true", 'B',0x42],
    ['key_c', "true", 'C', 0x43],
    ['key_d', "true", 'D', 0x44],
    ['key_e', "true", 'E', 0x45],
    ['key_f', "true", 'F', 0x46],
    ['key_g', "true", 'G', 0x47],
    ['key_h', "true", 'H', 0x48],
    ['key_i', "true", 'I',0x49],
    ['key_j', "true", 'J', 0x4A],
    ['key_k', "true", 'K', 0x4B],
    ['key_l', "true", 'L', 0x4C],
    ['key_m', "true", 'M',0x4D],
    ['key_n', "true", 'N', 0x4E],
    ['key_o', "true", 'O', 0x4F],
    ['key_p', "true", 'P', 0x50],
    ['key_q', "true", 'Q', 0x51],
    ['key_r', "true", 'R', 0x52],
    ['key_s', "true", 'S', 0x53],
    ['key_t', "true", 'T', 0x54],
    ['key_u', "true", 'U', 0x55],
    ['key_v', "true", 'V', 0x56],
    ['key_w', "true", 'W', 0x57],
    ['key_x', "true", 'X', 0x58],
    ['key_y', "true", 'Y', 0x59],
    ['key_z', "true", 'Z', 0x5A],
    ['key_left_bracket', "false", '[', 0x5B],
    ['key_backslash', "false", '\\', 0x5C],
    ['key_right_bracket', "false", ']', 0x5D],
    ['key_six', "true", '^', 0x5E],
    ['key_hyphen', "true", '_', 0x5F],
    ['key_accent', "false", '`', 0x60],
    ['key_a', "false", 'a', 0x61],
    ['key_b', "false", 'b', 0x62],
    ['key_c', "false", 'c', 0x63],
    ['key_d', "false", 'd', 0x64],
    ['key_e', "false", 'e', 0x65],
    ['key_f', "false", 'f', 0x66],
    ['key_g', "false", 'g', 0x67],
    ['key_h', "false", 'h', 0x68],
    ['key_i', "false", 'i', 0x69],
    ['key_j', "false", 'j', 0x6A],
    ['key_k', "false", 'k', 0x6B],
    ['key_l', "false", 'l', 0x6C],
    ['key_m', "false", 'm', 0x6D],
    ['key_n', "false", 'n', 0x6E],
    ['key_o', "false", 'o', 0x6F],
    ['key_p', "false", 'p', 0x70],
    ['key_q', "false", 'q', 0x71],
    ['key_r', "false", 'r', 0x72],
    ['key_s', "false", 's', 0x73],
    ['key_t', "false", 't', 0x74],
    ['key_u', "false", 'u', 0x75],
    ['key_v', "false", 'v', 0x76],
    ['key_w', "false", 'w', 0x77],
    ['key_x', "false", 'x', 0x78],
    ['key_y', "false", 'y', 0x79],
    ['key_z', "false", 'z', 0x7A],
    ['key_left_bracket', "true", '{', 0x7B],
    ['key_backslash', "true", '|', 0x7C],
    ['key_right_bracket', "true", '}', 0x7D],
    ['key_accent', "true", '~', 0x7E]
  ];

  return layout_to_html;
}
