---
---

// taja.js > match_key = function(key) [글쇠, 손가락, ID, 갈마들이]
function get_taja_hangeul(type) {
  var K2_2_ksx5002 = {
    '<strong class="cheot">ㄱ</strong>':  ['r', 7, "key_r"],
    '<strong class="cheot">ㄲ</strong>':  ['R', 7, "key_r"],
    '<strong class="cheot">ㄴ</strong>':  ['s', 9, "key_s"],
    '<strong class="cheot">ㄷ</strong>':  ['e', 8, "key_e"],
    '<strong class="cheot">ㄸ</strong>':  ['E', 8, "key_e"],
    '<strong class="cheot">ㄹ</strong>':  ['f', 7, "key_f"],
    '<strong class="cheot">ㅁ</strong>':  ['a', 10, "key_a"],
    '<strong class="cheot">ㅂ</strong>':  ['q', 10, "key_q"],
    '<strong class="cheot">ㅃ</strong>':  ['Q', 10, "key_q"],
    '<strong class="cheot">ㅅ</strong>':  ['t', 7, "key_t"],
    '<strong class="cheot">ㅆ</strong>':  ['T', 7, "key_t"],
    '<strong class="cheot">ㅇ</strong>':  ['d', 8, "key_d"],
    '<strong class="cheot">ㅈ</strong>':  ['w', 9, "key_w"],
    '<strong class="cheot">ㅉ</strong>':  ['W', 9, "key_w"],
    '<strong class="cheot">ㅊ</strong>':  ['c', 8, "key_c"],
    '<strong class="cheot">ㅋ</strong>':  ['z', 10, "key_z"],
    '<strong class="cheot">ㅌ</strong>':  ['x', 9, "key_x"],
    '<strong class="cheot">ㅍ</strong>':  ['v', 7, "key_v"],
    '<strong class="cheot">ㅎ</strong>':  ['g', 7, "key_g"],
    '<strong class="gawit">ㅏ</strong>': ['k', 3, "key_k"],
    '<strong class="gawit">ㅐ</strong>': ['o', 4, "key_o"],
    '<strong class="gawit">ㅒ</strong>': ['O', 4, "key_o"],
    '<strong class="gawit">ㅑ</strong>': ['i', 3, "key_i"],
    '<strong class="gawit">ㅓ</strong>': ['j', 2, "key_j"],
    '<strong class="gawit">ㅔ</strong>': ['p', 5, "key_p"],
    '<strong class="gawit">ㅖ</strong>': ['P', 5, "key_p"],
    '<strong class="gawit">ㅕ</strong>': ['u', 2, "key_u"],
    '<strong class="gawit">ㅗ</strong>': ['h', 2, "key_h"],
    '<strong class="gawit">ㅛ</strong>': ['y', 2, "key_y"],
    '<strong class="gawit">ㅜ</strong>': ['n', 2, "key_n"],
    '<strong class="gawit">ㅠ</strong>': ['b', 7, "key_b"],
    '<strong class="gawit">ㅡ</strong>': ['m', 2, "key_m"],
    '<strong class="gawit">ㅣ</strong>': ['l', 4, "key_l"],
  };

  var K2_2sun_ksx5002 = {
    '<strong class="cheot">ㄱ</strong>':  ['r', 7, "key_r"],
    '<strong class="cheot">ㄴ</strong>':  ['s', 9, "key_s"],
    '<strong class="cheot">ㄷ</strong>':  ['e', 8, "key_e"],
    '<strong class="cheot">ㄹ</strong>':  ['f', 7, "key_f"],
    '<strong class="cheot">ㅁ</strong>':  ['a', 10, "key_a"],
    '<strong class="cheot">ㅂ</strong>':  ['q', 10, "key_q"],
    '<strong class="cheot">ㅅ</strong>':  ['t', 7, "key_t"],
    '<strong class="cheot">ㅇ</strong>':  ['d', 8, "key_d"],
    '<strong class="cheot">ㅈ</strong>':  ['w', 9, "key_w"],
    '<strong class="cheot">ㅊ</strong>':  ['c', 8, "key_c"],
    '<strong class="cheot">ㅋ</strong>':  ['z', 10, "key_z"],
    '<strong class="cheot">ㅌ</strong>':  ['x', 9, "key_x"],
    '<strong class="cheot">ㅍ</strong>':  ['v', 7, "key_v"],
    '<strong class="cheot">ㅎ</strong>':  ['g', 7, "key_g"],
    '<strong class="gawit">ㅏ</strong>': ['k', 3, "key_k"],
    '<strong class="gawit">ㅐ</strong>': ['o', 4, "key_o"],
    '<strong class="gawit">ㅑ</strong>': ['i', 3, "key_i"],
    '<strong class="gawit">ㅓ</strong>': ['j', 2, "key_j"],
    '<strong class="gawit">ㅔ</strong>': ['p', 5, "key_p"],
    '<strong class="gawit">ㅕ</strong>': ['u', 2, "key_u"],
    '<strong class="gawit">ㅗ</strong>': ['h', 2, "key_h"],
    '<strong class="gawit">ㅛ</strong>': ['y', 2, "key_y"],
    '<strong class="gawit">ㅜ</strong>': ['n', 2, "key_n"],
    '<strong class="gawit">ㅠ</strong>': ['b', 7, "key_b"],
    '<strong class="gawit">ㅡ</strong>': ['m', 2, "key_m"],
    '<strong class="gawit">ㅣ</strong>': ['l', 4, "key_l"],
  };

  var K2_2_kps9256 = {
    '<strong class="cheot">ㄱ</strong>':  ['s', 9, "key_s"],
    '<strong class="cheot">ㄴ</strong>':  ['f', 7, "key_f"],
    '<strong class="cheot">ㄷ</strong>':  ['e', 8, "key_e"],
    '<strong class="cheot">ㄹ</strong>':  ['r', 7, "key_r"],
    '<strong class="cheot">ㅁ</strong>':  ['w', 9, "key_w"],
    '<strong class="cheot">ㅂ</strong>':  ['q', 10, "key_q"],
    '<strong class="cheot">ㅅ</strong>':  ['g', 7, "key_g"],
    '<strong class="cheot">ㅇ</strong>':  ['d', 8, "key_d"],
    '<strong class="cheot">ㅈ</strong>':  ['a', 10, "key_a"],
    '<strong class="cheot">ㅊ</strong>':  ['v', 7, "key_v"],
    '<strong class="cheot">ㅋ</strong>':  ['z', 10, "key_z"],
    '<strong class="cheot">ㅌ</strong>':  ['x', 9, "key_x"],
    '<strong class="cheot">ㅍ</strong>':  ['c', 8, "key_c"],
    '<strong class="cheot">ㅎ</strong>':  ['t', 7, "key_t"],
    '<strong class="gawit">ㅏ</strong>': ['j', 2, "key_j"],
    '<strong class="gawit">ㅐ</strong>': ['o', 4, "key_o"],
    '<strong class="gawit">ㅑ</strong>': ['m', 2, "key_m"],
    '<strong class="gawit">ㅓ</strong>': ['i', 3, "key_i"],
    '<strong class="gawit">ㅔ</strong>': ['p', 5, "key_p"],
    '<strong class="gawit">ㅕ</strong>': ['y', 2, "key_y"],
    '<strong class="gawit">ㅗ</strong>': ['h', 2, "key_h"],
    '<strong class="gawit">ㅛ</strong>': ['n', 2, "key_n"],
    '<strong class="gawit">ㅜ</strong>': ['u', 2, "key_u"],
    '<strong class="gawit">ㅠ</strong>': ['b', 7, "key_b"],
    '<strong class="gawit">ㅡ</strong>': ['l', 4, "key_l"],
    '<strong class="gawit">ㅣ</strong>': ['k', 3, "key_k"],
  };


  var K3_3_90 = {
    '<strong class="cheot">ㄱ</strong>':  ['k', 8, "key_k"],
    '<strong class="cheot">ㄴ</strong>':  ['h', 7, "key_h"],
    '<strong class="cheot">ㄷ</strong>':  ['u', 7, "key_u"],
    '<strong class="cheot">ㄹ</strong>':  ['y', 7, "key_y"],
    '<strong class="cheot">ㅁ</strong>':  ['i', 8, "key_i"],
    '<strong class="cheot">ㅂ</strong>':  [';', 10, "key_semicolon"],
    '<strong class="cheot">ㅅ</strong>':  ['n', 7, "key_n"],
    '<strong class="cheot">ㅇ</strong>':  ['j', 7, "key_j"],
    '<strong class="cheot">ㅈ</strong>':  ['l', 9, "key_l"],
    '<strong class="cheot">ㅊ</strong>':  ['o', 9, "key_o"],
    '<strong class="cheot">ㅋ</strong>':  ['0', 10, "key_zero"],
    '<strong class="cheot">ㅌ</strong>':  ['\'', 10, "key_apostrophe"],
    '<strong class="cheot">ㅍ</strong>':  ['p', 10, "key_p"],
    '<strong class="cheot">ㅎ</strong>':  ['m', 7, "key_m"],
    '<strong class="gawit">ㅏ</strong>': ['f', 2, "key_f"],
    '<strong class="gawit">ㅐ</strong>': ['r', 2, "key_r"],
    '<strong class="gawit">ㅒ</strong>': ['R', 2, "key_r"],
    '<strong class="gawit">ㅑ</strong>': ['6', 2, "key_six"],
    '<strong class="gawit">ㅓ</strong>': ['t', 2, "key_t"],
    '<strong class="gawit">ㅔ</strong>': ['c', 3, "key_c"],
    '<strong class="gawit">ㅖ</strong>': ['7', 7, "key_seven"],
    '<strong class="gawit">ㅕ</strong>': ['e', 3, "key_e"],
    '<strong class="gawit">ㅗ</strong>': ['v', 2, "key_v"],
    '<strong class="gawit">ㅛ</strong>': ['4', 2, "key_four"],
    '<strong class="gawit">ㅜ</strong>': ['b', 2, "key_b"],
    '<strong class="gawit">ㅠ</strong>': ['5', 2, "key_five"],
    '<strong class="gawit">ㅡ</strong>': ['g', 2, "key_g"],
    '<strong class="gawit">ㅣ</strong>': ['d', 3, "key_d"],
    '<strong class="gawit">ㅢ</strong>': ['8', 8, "key_eight"],
    '<strong class="gawit_right">ㅗ(↘)</strong>': ['/', 10, "key_forwardslash"],
    '<strong class="gawit_right">ㅜ(↗)</strong>': ['9', 9, "key_nine"],
    '<strong class="ggeut">ㄱ</strong>': ['x', 4, "key_x"],
    '<strong class="ggeut">ㄴ</strong>': ['s', 4, "key_s"],
    '<strong class="ggeut">ㄷ</strong>': ['A', 5, "key_a"],
    '<strong class="ggeut">ㄹ</strong>': ['w', 4, "key_w"],
    '<strong class="ggeut">ㅁ</strong>': ['z', 5, "key_z"],
    '<strong class="ggeut">ㅂ</strong>': ['3', 3, "key_three"],
    '<strong class="ggeut">ㅅ</strong>': ['q', 5, "key_q"],
    '<strong class="ggeut">ㅆ</strong>': ['2', 4, "key_two"],
    '<strong class="ggeut">ㅇ</strong>': ['a', 5, "key_a"],
    '<strong class="ggeut">ㅈ</strong>': ['!', 5, "key_one"],
    '<strong class="ggeut">ㅊ</strong>': ['Z', 5, "key_z"],
    '<strong class="ggeut">ㅋ</strong>': ['E', 3, "key_e"],
    '<strong class="ggeut">ㅌ</strong>': ['W', 4, "key_w"],
    '<strong class="ggeut">ㅍ</strong>': ['Q', 5, "key_q"],
    '<strong class="ggeut">ㅎ</strong>': ['1', 5, "key_one"],
    '<strong class="ggeut">ㄲ</strong>': ['F', 2, "key_f"],
    '<strong class="ggeut">ㄺ</strong>': ['D', 3, "key_d"],
    '<strong class="ggeut">ㅀ</strong>': ['V', 2, "key_v"],
    '<strong class="ggeut">ㄶ</strong>': ['S', 4, "key_s"],
    '<strong class="ggeut">ㄻ</strong>': ['C', 3, "key_c"],
    '<strong class="ggeut">ㅄ</strong>': ['X', 4, "key_x"],
  };

  var K3_3_91 = {
    '<strong class="cheot">ㄱ</strong>':  ['k', 8, "key_k"],
    '<strong class="cheot">ㄴ</strong>':  ['h', 7, "key_h"],
    '<strong class="cheot">ㄷ</strong>':  ['u', 7, "key_u"],
    '<strong class="cheot">ㄹ</strong>':  ['y', 7, "key_y"],
    '<strong class="cheot">ㅁ</strong>':  ['i', 8, "key_i"],
    '<strong class="cheot">ㅂ</strong>':  [';', 10, "key_semicolon"],
    '<strong class="cheot">ㅅ</strong>':  ['n', 7, "key_n"],
    '<strong class="cheot">ㅇ</strong>':  ['j', 7, "key_j"],
    '<strong class="cheot">ㅈ</strong>':  ['l', 9, "key_l"],
    '<strong class="cheot">ㅊ</strong>':  ['o', 9, "key_o"],
    '<strong class="cheot">ㅋ</strong>':  ['0', 10, "key_zero"],
    '<strong class="cheot">ㅌ</strong>':  ['\'', 10, "key_apostrophe"],
    '<strong class="cheot">ㅍ</strong>':  ['p', 10, "key_p"],
    '<strong class="cheot">ㅎ</strong>':  ['m', 7, "key_m"],
    '<strong class="gawit">ㅏ</strong>': ['f', 2, "key_f"],
    '<strong class="gawit">ㅐ</strong>': ['r', 2, "key_r"],
    '<strong class="gawit">ㅒ</strong>': ['G', 2, "key_G"],
    '<strong class="gawit">ㅑ</strong>': ['6', 2, "key_six"],
    '<strong class="gawit">ㅓ</strong>': ['t', 2, "key_t"],
    '<strong class="gawit">ㅔ</strong>': ['c', 3, "key_c"],
    '<strong class="gawit">ㅖ</strong>': ['7', 7, "key_seven"],
    '<strong class="gawit">ㅕ</strong>': ['e', 3, "key_e"],
    '<strong class="gawit">ㅗ</strong>': ['v', 2, "key_v"],
    '<strong class="gawit">ㅛ</strong>': ['4', 2, "key_four"],
    '<strong class="gawit">ㅜ</strong>': ['b', 2, "key_b"],
    '<strong class="gawit">ㅠ</strong>': ['5', 2, "key_five"],
    '<strong class="gawit">ㅡ</strong>': ['g', 2, "key_g"],
    '<strong class="gawit">ㅣ</strong>': ['d', 3, "key_d"],
    '<strong class="gawit">ㅢ</strong>': ['8', 8, "key_eight"],
    '<strong class="gawit_right">ㅗ(↘)</strong>': ['/', 10, "key_forwardslash"],
    '<strong class="gawit_right">ㅜ(↗)</strong>': ['9', 9, "key_nine"],
    '<strong class="ggeut">ㄱ</strong>': ['x', 4, "key_x"],
    '<strong class="ggeut">ㄴ</strong>': ['s', 4, "key_s"],
    '<strong class="ggeut">ㄷ</strong>': ['A', 5, "key_a"],
    '<strong class="ggeut">ㄹ</strong>': ['w', 4, "key_w"],
    '<strong class="ggeut">ㅁ</strong>': ['z', 5, "key_z"],
    '<strong class="ggeut">ㅂ</strong>': ['3', 3, "key_three"],
    '<strong class="ggeut">ㅅ</strong>': ['q', 5, "key_q"],
    '<strong class="ggeut">ㅆ</strong>': ['2', 4, "key_two"],
    '<strong class="ggeut">ㅇ</strong>': ['a', 5, "key_a"],
    '<strong class="ggeut">ㅈ</strong>': ['#', 3, "key_three"],
    '<strong class="ggeut">ㅊ</strong>': ['Z', 5, "key_z"],
    '<strong class="ggeut">ㅋ</strong>': ['C', 3, "key_c"],
    '<strong class="ggeut">ㅌ</strong>': ['W', 4, "key_w"],
    '<strong class="ggeut">ㅍ</strong>': ['Q', 5, "key_q"],
    '<strong class="ggeut">ㅎ</strong>': ['1', 5, "key_one"],
    '<strong class="ggeut">ㄲ</strong>': ['!', 5, "key_one"],
    '<strong class="ggeut">ㄺ</strong>': ['@', 4, "key_two"],
    '<strong class="ggeut">ㄿ</strong>': ['$', 2, "key_four"],
    '<strong class="ggeut">ㄾ</strong>': ['%', 2, "key_five"],
    '<strong class="ggeut">ㄵ</strong>': ['E', 3, "key_e"],
    '<strong class="ggeut">ㅀ</strong>': ['R', 2, "key_r"],
    '<strong class="ggeut">ㄽ</strong>': ['T', 2, "key_t"],
    '<strong class="ggeut">ㄶ</strong>': ['S', 4, "key_s"],
    '<strong class="ggeut">ㄼ</strong>': ['D', 3, "key_d"],
    '<strong class="ggeut">ㄻ</strong>': ['F', 2, "key_f"],
    '<strong class="ggeut">ㅄ</strong>': ['X', 4, "key_x"],
    '<strong class="ggeut">ㄳ</strong>': ['V', 2, "key_v"],
  };

  var K3_3_2012 = {
    '<strong class="cheot">ㄱ</strong>':  ['k', 8, "key_k"],
    '<strong class="cheot">ㄴ</strong>':  ['h', 7, "key_h"],
    '<strong class="cheot">ㄷ</strong>':  ['u', 7, "key_u"],
    '<strong class="cheot">ㄹ</strong>':  ['y', 7, "key_y"],
    '<strong class="cheot">ㅁ</strong>':  ['i', 8, "key_i"],
    '<strong class="cheot">ㅂ</strong>':  [';', 10, "key_semicolon"],
    '<strong class="cheot">ㅅ</strong>':  ['n', 7, "key_n"],
    '<strong class="cheot">ㅇ</strong>':  ['j', 7, "key_j"],
    '<strong class="cheot">ㅈ</strong>':  ['l', 9, "key_l"],
    '<strong class="cheot">ㅊ</strong>':  ['o', 9, "key_o"],
    '<strong class="cheot">ㅋ</strong>':  ['0', 10, "key_zero"],
    '<strong class="cheot">ㅌ</strong>':  ['\'', 10, "key_apostrophe"],
    '<strong class="cheot">ㅍ</strong>':  ['p', 10, "key_p"],
    '<strong class="cheot">ㅎ</strong>':  ['m', 7, "key_m"],
    '<strong class="gawit">ㅏ</strong>': ['f', 2, "key_f"],
    '<strong class="gawit">ㅐ</strong>': ['t', 2, "key_t"],
    '<strong class="gawit">ㅒ</strong>': ['T', 2, "key_t"],
    '<strong class="gawit">ㅑ</strong>': ['6', 2, "key_six"],
    '<strong class="gawit">ㅓ</strong>': ['r', 2, "key_r"],
    '<strong class="gawit">ㅔ</strong>': ['c', 3, "key_c"],
    '<strong class="gawit">ㅖ</strong>': ['7', 7, "key_seven"],
    '<strong class="gawit">ㅕ</strong>': ['e', 3, "key_e"],
    '<strong class="gawit">ㅗ</strong>': ['v', 2, "key_v"],
    '<strong class="gawit">ㅛ</strong>': ['4', 2, "key_four"],
    '<strong class="gawit">ㅜ</strong>': ['b', 2, "key_b"],
    '<strong class="gawit">ㅠ</strong>': ['5', 2, "key_five"],
    '<strong class="gawit">ㅡ</strong>': ['g', 2, "key_g"],
    '<strong class="gawit">ㅣ</strong>': ['d', 3, "key_d"],
    '<strong class="gawit">ㅢ</strong>': ['8', 8, "key_eight"],
    '<strong class="gawit_right">ㅗ(↘)</strong>': ['/', 10, "key_forwardslash"],
    '<strong class="gawit_right">ㅜ(↗)</strong>': ['9', 9, "key_nine"],
    '<strong class="ggeut">ㄱ</strong>': ['x', 4, "key_x"],
    '<strong class="ggeut">ㄴ</strong>': ['s', 4, "key_s"],
    '<strong class="ggeut">ㄷ</strong>': ['A', 5, "key_a"],
    '<strong class="ggeut">ㄹ</strong>': ['w', 4, "key_w"],
    '<strong class="ggeut">ㅁ</strong>': ['z', 5, "key_z"],
    '<strong class="ggeut">ㅂ</strong>': ['3', 3, "key_three"],
    '<strong class="ggeut">ㅅ</strong>': ['q', 5, "key_q"],
    '<strong class="ggeut">ㅆ</strong>': ['2', 4, "key_two"],
    '<strong class="ggeut">ㅇ</strong>': ['a', 5, "key_a"],
    '<strong class="ggeut">ㅈ</strong>': ['E', 3, "key_e"],
    '<strong class="ggeut">ㅊ</strong>': ['Z', 5, "key_z"],
    '<strong class="ggeut">ㅋ</strong>': ['C', 3, "key_c"],
    '<strong class="ggeut">ㅌ</strong>': ['W', 4, "key_w"],
    '<strong class="ggeut">ㅍ</strong>': ['Q', 5, "key_q"],
    '<strong class="ggeut">ㅎ</strong>': ['1', 5, "key_one"],
    '<strong class="ggeut">ㄶ</strong>': ['S', 4, "key_s"],
    '<strong class="ggeut">ㅄ</strong>': ['X', 4, "key_x"],
    '<strong class="ggeut">ㄺ</strong>': ['D', 3, "key_d"],
    '<strong class="ggeut">ㅀ</strong>': ['R', 2, "key_r"],
    '<strong class="ggeut">ㄲ</strong>': ['V', 2, "key_v"],
  };

  var K3_3_2015 = {
    '<strong class="cheot">ㄱ</strong>':  ['k', 8, "key_k"],
    '<strong class="cheot">ㄴ</strong>':  ['h', 7, "key_h"],
    '<strong class="cheot">ㄷ</strong>':  ['u', 7, "key_u"],
    '<strong class="cheot">ㄹ</strong>':  ['y', 7, "key_y"],
    '<strong class="cheot">ㅁ</strong>':  ['i', 8, "key_i"],
    '<strong class="cheot">ㅂ</strong>':  [';', 10, "key_semicolon"],
    '<strong class="cheot">ㅅ</strong>':  ['n', 7, "key_n"],
    '<strong class="cheot">ㅇ</strong>':  ['j', 7, "key_j"],
    '<strong class="cheot">ㅈ</strong>':  ['l', 9, "key_l"],
    '<strong class="cheot">ㅊ</strong>':  ['o', 9, "key_o"],
    '<strong class="cheot">ㅋ</strong>':  ['0', 9, "key_zero"],
    '<strong class="cheot">ㅌ</strong>':  ['\'', 10, "key_apostrophe"],
    '<strong class="cheot">ㅍ</strong>':  ['p', 10, "key_p"],
    '<strong class="cheot">ㅎ</strong>':  ['m', 8, "key_m"],
    '<strong class="gawit">ㅏ</strong>': ['f', 2, "key_f"],
    '<strong class="gawit">ㅐ</strong>': ['t', 2, "key_t"],
    '<strong class="gawit">ㅒ</strong>': ['T', 2, "key_t", 't'],
    '<strong class="gawit">ㅑ</strong>': ['6', 2, "key_six"],
    '<strong class="gawit">ㅓ</strong>': ['r', 2, "key_r"],
    '<strong class="gawit">ㅔ</strong>': ['c', 3, "key_c"],
    '<strong class="gawit">ㅖ</strong>': ['7', 7, "key_seven"],
    '<strong class="gawit">ㅕ</strong>': ['e', 3, "key_e"],
    '<strong class="gawit">ㅗ</strong>': ['v', 2, "key_v"],
    '<strong class="gawit">ㅛ</strong>': ['4', 3, "key_four"],
    '<strong class="gawit">ㅜ</strong>': ['b', 2, "key_b"],
    '<strong class="gawit">ㅠ</strong>': ['5', 2, "key_five"],
    '<strong class="gawit">ㅡ</strong>': ['g', 2, "key_g"],
    '<strong class="gawit">ㅣ</strong>': ['d', 3, "key_d"],
    '<strong class="gawit">ㅢ</strong>': ['8', 8, "key_eight"],
    '<strong class="gawit_right">ㅗ(↘)</strong>': ['/', 10, "key_forwardslash"],
    '<strong class="gawit_right">ㅜ(↗)</strong>': ['9', 8, "key_nine"],
    '<strong class="ggeut">ㄱ</strong>': ['x', 4, "key_x"],
    '<strong class="ggeut">ㄴ</strong>': ['s', 4, "key_s"],
    '<strong class="ggeut">ㄷ</strong>': ['1', 5, "key_one"],
    '<strong class="ggeut">ㄹ</strong>': ['w', 4, "key_w"],
    '<strong class="ggeut">ㅁ</strong>': ['z', 5, "key_z"],
    '<strong class="ggeut">ㅂ</strong>': ['3', 3, "key_three"],
    '<strong class="ggeut">ㅅ</strong>': ['q', 5, "key_q"],
    '<strong class="ggeut">ㅆ</strong>': ['2', 4, "key_two"],
    '<strong class="ggeut">ㅇ</strong>': ['a', 5, "key_a"],
    '<strong class="ggeut">ㅈ</strong>': ['E', 3, "key_e", 'e'],
    '<strong class="ggeut">ㅊ</strong>': ['R', 2, "key_r", 'r'],
    '<strong class="ggeut">ㅋ</strong>': ['V', 2, "key_v", 'v'],
    '<strong class="ggeut">ㅌ</strong>': ['C', 3, "key_c", 'c'],
    '<strong class="ggeut">ㅍ</strong>': ['F', 2, "key_f", 'f'],
    '<strong class="ggeut">ㅎ</strong>': ['D', 3, "key_d", 'd'],
    '<strong>0</strong>': ['H', 7, "key_h"],
    '<strong>1</strong>': ['J', 7, "key_j"],
    '<strong>2</strong>': ['K', 8, "key_k"],
    '<strong>3</strong>': ['L', 9, "key_l"],
    '<strong>4</strong>': [':', 10, "key_semicolon"],
    '<strong>5</strong>': ['Y', 7, "key_y"],
    '<strong>6</strong>': ['U', 7, "key_u"],
    '<strong>7</strong>': ['I', 8, "key_i"],
    '<strong>8</strong>': ['O', 9, "key_o"],
    '<strong>9</strong>': ['P', 10, "key_p"],
  };

  var K3_3_2015_patal = {
    '<strong class="cheot">ㄱ</strong>':  ['k', 8, "key_k"],
    '<strong class="cheot">ㄴ</strong>':  ['h', 7, "key_h"],
    '<strong class="cheot">ㄷ</strong>':  ['u', 7, "key_u"],
    '<strong class="cheot">ㄹ</strong>':  ['y', 7, "key_y"],
    '<strong class="cheot">ㅁ</strong>':  ['i', 8, "key_i"],
    '<strong class="cheot">ㅂ</strong>':  [';', 10, "key_semicolon"],
    '<strong class="cheot">ㅅ</strong>':  ['n', 7, "key_n"],
    '<strong class="cheot">ㅇ</strong>':  ['j', 7, "key_j"],
    '<strong class="cheot">ㅈ</strong>':  ['l', 9, "key_l"],
    '<strong class="cheot">ㅊ</strong>':  ['o', 9, "key_o"],
    '<strong class="cheot">ㅋ</strong>':  ['0', 10, "key_zero"],
    '<strong class="cheot">ㅌ</strong>':  ['\'', 10, "key_apostrophe"],
    '<strong class="cheot">ㅍ</strong>':  ['p', 10, "key_p"],
    '<strong class="cheot">ㅎ</strong>':  ['m', 7, "key_m"],
    '<strong class="gawit">ㅏ</strong>': ['f', 2, "key_f"],
    '<strong class="gawit">ㅐ</strong>': ['t', 2, "key_t"],
    '<strong class="gawit">ㅒ</strong>': ['T', 2, "key_t", 't'],
    '<strong class="gawit">ㅑ</strong>': ['6', 2, "key_six"],
    '<strong class="gawit">ㅓ</strong>': ['r', 2, "key_r"],
    '<strong class="gawit">ㅔ</strong>': ['c', 3, "key_c"],
    '<strong class="gawit">ㅖ</strong>': ['7', 7, "key_seven"],
    '<strong class="gawit">ㅕ</strong>': ['e', 3, "key_e"],
    '<strong class="gawit">ㅗ</strong>': ['v', 2, "key_v"],
    '<strong class="gawit">ㅛ</strong>': ['4', 2, "key_four"],
    '<strong class="gawit">ㅜ</strong>': ['b', 2, "key_b"],
    '<strong class="gawit">ㅠ</strong>': ['5', 2, "key_five"],
    '<strong class="gawit">ㅡ</strong>': ['g', 2, "key_g"],
    '<strong class="gawit">ㅣ</strong>': ['d', 3, "key_d"],
    '<strong class="gawit">ㅢ</strong>': ['8', 8, "key_eight"],
    '<strong class="gawit_right">ㅗ(↘)</strong>': ['/', 10, "key_forwardslash"],
    '<strong class="gawit_right">ㅜ(↗)</strong>': ['9', 9, "key_nine"],
    '<strong class="ggeut">ㄱ</strong>': ['x', 4, "key_x"],
    '<strong class="ggeut">ㄴ</strong>': ['s', 4, "key_s"],
    '<strong class="ggeut">ㄷ</strong>': ['1', 5, "key_one"],
    '<strong class="ggeut">ㄹ</strong>': ['w', 4, "key_w"],
    '<strong class="ggeut">ㅁ</strong>': ['z', 5, "key_z"],
    '<strong class="ggeut">ㅂ</strong>': ['3', 3, "key_three"],
    '<strong class="ggeut">ㅅ</strong>': ['q', 5, "key_q"],
    '<strong class="ggeut">ㅆ</strong>': ['2', 4, "key_two"],
    '<strong class="ggeut">ㅇ</strong>': ['a', 5, "key_a"],
    '<strong class="ggeut">ㅈ</strong>': ['E', 3, "key_e", 'e'],
    '<strong class="ggeut">ㅊ</strong>': ['R', 2, "key_r", 'r'],
    '<strong class="ggeut">ㅋ</strong>': ['V', 2, "key_v", 'v'],
    '<strong class="ggeut">ㅌ</strong>': ['C', 3, "key_c", 'c'],
    '<strong class="ggeut">ㅍ</strong>': ['F', 2, "key_f", 'f'],
    '<strong class="ggeut">ㅎ</strong>': ['D', 3, "key_d", 'd'],
  };

  var K3_3shin_1995 = {
    '<strong class="cheot">ㄱ</strong>':  ['k', 8, "key_k"],
    '<strong class="cheot">ㄴ</strong>':  ['h', 7, "key_h"],
    '<strong class="cheot">ㄷ</strong>':  ['u', 7, "key_u"],
    '<strong class="cheot">ㄹ</strong>':  ['y', 7, "key_y"],
    '<strong class="cheot">ㅁ</strong>':  ['i', 8, "key_i"],
    '<strong class="cheot">ㅂ</strong>':  [';', 10, "key_semicolon"],
    '<strong class="cheot">ㅅ</strong>':  ['n', 7, "key_n"],
    '<strong class="cheot">ㅇ</strong>':  ['j', 7, "key_j"],
    '<strong class="cheot">ㅈ</strong>':  ['l', 9, "key_l"],
    '<strong class="cheot">ㅊ</strong>':  ['o', 9, "key_o"],
    '<strong class="cheot">ㅋ</strong>':  ['/', 10, "key_forwardslash"],
    '<strong class="cheot">ㅌ</strong>':  ['\'', 10, "key_apostrophe"],
    '<strong class="cheot">ㅍ</strong>':  ['p', 10, "key_p"],
    '<strong class="cheot">ㅎ</strong>':  ['m', 7, "key_m"],
    '<strong class="gawit">ㅏ</strong>': ['F', 2, "key_f", 'f'],
    '<strong class="gawit">ㅐ</strong>': ['R', 2, "key_r", 'r'],
    '<strong class="gawit">ㅒ</strong>': ['A', 5, "key_a", 'a'],
    '<strong class="gawit">ㅑ</strong>': ['W', 4, "key_w", 'w'],
    '<strong class="gawit">ㅓ</strong>': ['T', 2, "key_t", 't'],
    '<strong class="gawit">ㅔ</strong>': ['C', 3, "key_c", 'c'],
    '<strong class="gawit">ㅖ</strong>': ['S', 4, "key_s", 's'],
    '<strong class="gawit">ㅕ</strong>': ['E', 3, "key_e", 'e'],
    '<strong class="gawit">ㅗ</strong>': ['V', 2, "key_v", 'v'],
    '<strong class="gawit">ㅛ</strong>': ['X', 4, "key_x", 'x'],
    '<strong class="gawit">ㅜ</strong>': ['B', 2, "key_b", 'b'],
    '<strong class="gawit">ㅠ</strong>': ['Z', 5, "key_z", 'z'],
    '<strong class="gawit">ㅡ</strong>': ['G', 2, "key_g", 'g'],
    '<strong class="gawit">ㅣ</strong>': ['D', 3, "key_d", 'd'],
    '<strong class="gawit">ㅢ</strong>': ['Q', 5, "key_q", 'q'],
    '<strong class="gawit_right">ㅜ(↗)</strong>': ['I', 8, "key_i", 'i'],
    '<strong class="gawit_right">ㅗ(↗)</strong>': ['P', 10, "key_p", 'p'],
    '<strong class="gawit_right">ㅗ(↘)</strong>': ['/', 10, "key_forwardslash", '?'],
    '<strong class="gawit_right">ㅜ(↗)</strong>': ['O', 9, "key_o", 'o'],
    '<strong class="ggeut">ㄱ</strong>': ['x', 4, "key_x"],
    '<strong class="ggeut">ㄴ</strong>': ['s', 4, "key_s"],
    '<strong class="ggeut">ㄷ</strong>': ['r', 2, "key_r"],
    '<strong class="ggeut">ㄹ</strong>': ['w', 4, "key_w"],
    '<strong class="ggeut">ㅁ</strong>': ['z', 5, "key_z"],
    '<strong class="ggeut">ㅂ</strong>': ['e', 3, "key_e"],
    '<strong class="ggeut">ㅅ</strong>': ['q', 5, "key_q"],
    '<strong class="ggeut">ㅆ</strong>': ['b', 2, "key_b"],
    '<strong class="ggeut">ㅇ</strong>': ['a', 5, "key_a"],
    '<strong class="ggeut">ㅈ</strong>': ['f', 2, "key_f"],
    '<strong class="ggeut">ㅊ</strong>': ['c', 3, "key_c"],
    '<strong class="ggeut">ㅎ</strong>': ['d', 3, "key_d"],
    '<strong class="ggeut">ㅌ</strong>': ['t', 2, "key_t"],
    '<strong class="ggeut">ㅋ</strong>': ['v', 2, "key_v"],
    '<strong class="ggeut">ㅍ</strong>': ['g', 2, "key_g"],
  };

  var K3_3shin_2003 = {
    '<strong class="cheot">ㄱ</strong>':  ['k', 8, "key_k"],
    '<strong class="cheot">ㄴ</strong>':  ['h', 7, "key_h"],
    '<strong class="cheot">ㄷ</strong>':  ['u', 7, "key_u"],
    '<strong class="cheot">ㄹ</strong>':  ['y', 7, "key_y"],
    '<strong class="cheot">ㅁ</strong>':  ['i', 8, "key_i"],
    '<strong class="cheot">ㅂ</strong>':  [';', 10, "key_semicolon"],
    '<strong class="cheot">ㅅ</strong>':  ['n', 7, "key_n"],
    '<strong class="cheot">ㅇ</strong>':  ['j', 7, "key_j"],
    '<strong class="cheot">ㅈ</strong>':  ['l', 9, "key_l"],
    '<strong class="cheot">ㅊ</strong>':  ['o', 9, "key_o"],
    '<strong class="cheot">ㅋ</strong>':  ['/', 10, "key_forwardslash"],
    '<strong class="cheot">ㅌ</strong>':  ['\'', 10, "key_apostrophe"],
    '<strong class="cheot">ㅍ</strong>':  ['p', 10, "key_p"],
    '<strong class="cheot">ㅎ</strong>':  ['m', 7, "key_m"],
    '<strong class="gawit">ㅏ</strong>': ['F', 2, "key_f", 'f'],
    '<strong class="gawit">ㅐ</strong>': ['R', 2, "key_r", 'r'],
    '<strong class="gawit">ㅒ</strong>': ['Q', 5, "key_q", 'q'],
    '<strong class="gawit">ㅑ</strong>': ['W', 4, "key_w", 'w'],
    '<strong class="gawit">ㅓ</strong>': ['T', 2, "key_t", 't'],
    '<strong class="gawit">ㅔ</strong>': ['C', 3, "key_c", 'c'],
    '<strong class="gawit">ㅖ</strong>': ['S', 4, "key_s", 's'],
    '<strong class="gawit">ㅕ</strong>': ['E', 3, "key_e", 'e'],
    '<strong class="gawit">ㅗ</strong>': ['V', 2, "key_v", 'v'],
    '<strong class="gawit">ㅛ</strong>': ['X', 4, "key_x", 'x'],
    '<strong class="gawit">ㅜ</strong>': ['B', 2, "key_b", 'b'],
    '<strong class="gawit">ㅠ</strong>': ['A', 5, "key_a", 'a'],
    '<strong class="gawit">ㅡ</strong>': ['G', 2, "key_g", 'g'],
    '<strong class="gawit">ㅣ</strong>': ['D', 3, "key_d", 'd'],
    '<strong class="gawit">ㅢ</strong>': ['I', 8, "key_i", 'i'],
    '<strong class="gawit_right">ㅗ(↗)</strong>': ['P', 10, "key_p", 'p'],
    '<strong class="gawit_right">ㅗ(↘)</strong>': ['/', 10, "key_forwardslash", '?'],
    '<strong class="gawit_right">ㅜ(↗)</strong>': ['O', 9, "key_o", 'o'],
    '<strong class="gawit_right">ㆍ(↗아래아)</strong>': ['[', 10, "key_left_bracket"],
    '<strong class="ggeut">ㄱ</strong>': ['x', 4, "key_x"],
    '<strong class="ggeut">ㄴ</strong>': ['s', 4, "key_s"],
    '<strong class="ggeut">ㄷ</strong>': ['d', 3, "key_d"],
    '<strong class="ggeut">ㄹ</strong>': ['w', 4, "key_w"],
    '<strong class="ggeut">ㅁ</strong>': ['z', 5, "key_z"],
    '<strong class="ggeut">ㅂ</strong>': ['e', 3, "key_e"],
    '<strong class="ggeut">ㅅ</strong>': ['q', 5, "key_q"],
    '<strong class="ggeut">ㅆ</strong>': ['f', 2, "key_f"],
    '<strong class="ggeut">ㅇ</strong>': ['a', 5, "key_a"],
    '<strong class="ggeut">ㅈ</strong>': ['g', 2, "key_g"],
    '<strong class="ggeut">ㅊ</strong>': ['c', 3, "key_c"],
    '<strong class="ggeut">ㅎ</strong>': ['v', 2, "key_v"],
    '<strong class="ggeut">ㅌ</strong>': ['r', 2, "key_r"],
    '<strong class="ggeut">ㅋ</strong>': ['b', 2, "key_b"],
    '<strong class="ggeut">ㅍ</strong>': ['t', 2, "key_t"],
  };

  var K3_3shin_2012 = {
    '<strong class="cheot">ㄱ</strong>':  ['k', 8, "key_k"],
    '<strong class="cheot">ㄴ</strong>':  ['h', 7, "key_h"],
    '<strong class="cheot">ㄷ</strong>':  ['u', 7, "key_u"],
    '<strong class="cheot">ㄹ</strong>':  ['y', 7, "key_y"],
    '<strong class="cheot">ㅁ</strong>':  ['i', 8, "key_i"],
    '<strong class="cheot">ㅂ</strong>':  [';', 10, "key_semicolon"],
    '<strong class="cheot">ㅅ</strong>':  ['n', 7, "key_n"],
    '<strong class="cheot">ㅇ</strong>':  ['j', 7, "key_j"],
    '<strong class="cheot">ㅈ</strong>':  ['l', 9, "key_l"],
    '<strong class="cheot">ㅊ</strong>':  ['o', 9, "key_o"],
    '<strong class="cheot">ㅋ</strong>':  ['/', 10, "key_forwardslash"],
    '<strong class="cheot">ㅌ</strong>':  ['\'', 10, "key_apostrophe"],
    '<strong class="cheot">ㅍ</strong>':  ['p', 10, "key_p"],
    '<strong class="cheot">ㅎ</strong>':  ['m', 7, "key_m"],
    '<strong class="gawit">ㅏ</strong>': ['F', 2, "key_f", 'f'],
    '<strong class="gawit">ㅐ</strong>': ['T', 2, "key_t", 't'],
    '<strong class="gawit">ㅒ</strong>': ['Q', 5, "key_q", 'q'],
    '<strong class="gawit">ㅑ</strong>': ['W', 4, "key_w", 'w'],
    '<strong class="gawit">ㅓ</strong>': ['R', 2, "key_r", 'r'],
    '<strong class="gawit">ㅔ</strong>': ['C', 3, "key_c", 'c'],
    '<strong class="gawit">ㅖ</strong>': ['S', 4, "key_s", 's'],
    '<strong class="gawit">ㅕ</strong>': ['E', 3, "key_e", 'e'],
    '<strong class="gawit">ㅗ</strong>': ['V', 2, "key_v", 'v'],
    '<strong class="gawit">ㅛ</strong>': ['X', 4, "key_x", 'x'],
    '<strong class="gawit">ㅜ</strong>': ['B', 2, "key_b", 'b'],
    '<strong class="gawit">ㅠ</strong>': ['A', 5, "key_a", 'a'],
    '<strong class="gawit">ㅡ</strong>': ['G', 2, "key_g", 'g'],
    '<strong class="gawit">ㅣ</strong>': ['D', 3, "key_d", 'd'],
    '<strong class="gawit">ㅢ</strong>': ['I', 8, "key_i", 'i'],
    '<strong class="gawit">ㆍ(아래아)</strong>': ['Z', 5, "key_z", 'z'],
    '<strong class="gawit_right">ㅗ(↗)</strong>': ['P', 10, "key_p", 'p'],
    '<strong class="gawit_right">ㅗ(↘)</strong>': ['/', 10, "key_forwardslash", '?'],
    '<strong class="gawit_right">ㅜ(↗)</strong>': ['O', 9, "key_o", 'o'],
    '<strong class="gawit_right">ㆍ(↗아래아)</strong>': ['[', 10, "key_left_bracket"],
    '<strong class="ggeut">ㄱ</strong>': ['x', 4, "key_x"],
    '<strong class="ggeut">ㄴ</strong>': ['s', 4, "key_s"],
    '<strong class="ggeut">ㄷ</strong>': ['t', 2, "key_t"],
    '<strong class="ggeut">ㄹ</strong>': ['w', 4, "key_w"],
    '<strong class="ggeut">ㅁ</strong>': ['z', 5, "key_z"],
    '<strong class="ggeut">ㅂ</strong>': ['e', 3, "key_e"],
    '<strong class="ggeut">ㅅ</strong>': ['q', 5, "key_q"],
    '<strong class="ggeut">ㅆ</strong>': ['d', 3, "key_d"],
    '<strong class="ggeut">ㅇ</strong>': ['a', 5, "key_a"],
    '<strong class="ggeut">ㅈ</strong>': ['g', 2, "key_g"],
    '<strong class="ggeut">ㅊ</strong>': ['f', 2, "key_f"],
    '<strong class="ggeut">ㅎ</strong>': ['c', 3, "key_c"],
    '<strong class="ggeut">ㅌ</strong>': ['r', 2, "key_r"],
    '<strong class="ggeut">ㅋ</strong>': ['b', 2, "key_b"],
    '<strong class="ggeut">ㅍ</strong>': ['v', 2, "key_v"],
  };

  var K3_3shin_2015 = {
    '<strong class="cheot">ㄱ</strong>':  ['k', 8, "key_k"],
    '<strong class="cheot">ㄴ</strong>':  ['h', 7, "key_h"],
    '<strong class="cheot">ㄷ</strong>':  ['u', 7, "key_u"],
    '<strong class="cheot">ㄹ</strong>':  ['y', 7, "key_y"],
    '<strong class="cheot">ㅁ</strong>':  ['i', 8, "key_i"],
    '<strong class="cheot">ㅂ</strong>':  [';', 10, "key_semicolon"],
    '<strong class="cheot">ㅅ</strong>':  ['n', 7, "key_n"],
    '<strong class="cheot">ㅇ</strong>':  ['j', 7, "key_j"],
    '<strong class="cheot">ㅈ</strong>':  ['l', 9, "key_l"],
    '<strong class="cheot">ㅊ</strong>':  ['o', 9, "key_o"],
    '<strong class="cheot">ㅋ</strong>':  ['/', 10, "key_forwardslash"],
    '<strong class="cheot">ㅌ</strong>':  ['\'', 10, "key_apostrophe"],
    '<strong class="cheot">ㅍ</strong>':  ['p', 10, "key_p"],
    '<strong class="cheot">ㅎ</strong>':  ['m', 8, "key_m"],
    '<strong class="gawit">ㅏ</strong>': ['f', 2, "key_f"],
    '<strong class="gawit">ㅐ</strong>': ['r', 2, "key_r"],
    '<strong class="gawit">ㅒ</strong>': ['q', 5, "key_q"],
    '<strong class="gawit">ㅑ</strong>': ['a', 4, "key_a"],
    '<strong class="gawit">ㅓ</strong>': ['t', 2, "key_t"],
    '<strong class="gawit">ㅔ</strong>': ['c', 3, "key_c"],
    '<strong class="gawit">ㅖ</strong>': ['w', 4, "key_w"],
    '<strong class="gawit">ㅕ</strong>': ['e', 3, "key_e"],
    '<strong class="gawit">ㅗ</strong>': ['v', 2, "key_v"],
    '<strong class="gawit">ㅛ</strong>': ['x', 4, "key_x"],
    '<strong class="gawit">ㅜ</strong>': ['b', 2, "key_b"],
    '<strong class="gawit">ㅠ</strong>': ['z', 5, "key_z"],
    '<strong class="gawit">ㅡ</strong>': ['g', 2, "key_g"],
    '<strong class="gawit">ㅣ</strong>': ['d', 3, "key_d"],
    '<strong class="gawit">ㅢ</strong>': ['s', 4, "key_s"],
    '<strong class="gawit_right">ㅗ(↗)</strong>': ['P', 10, "key_p", 'p'],
    '<strong class="gawit_right">ㅗ(↘)</strong>': ['/', 10, "key_forwardslash", '?'],
    '<strong class="gawit_right">ㅜ(↗)</strong>': ['O', 9, "key_o", 'o'],
    '<strong class="ggeut">ㄱ</strong>': ['X', 4, "key_x", 'x'],
    '<strong class="ggeut">ㄴ</strong>': ['S', 4, "key_s", 's'],
    '<strong class="ggeut">ㄷ</strong>': ['G', 2, "key_g", 'g'],
    '<strong class="ggeut">ㄹ</strong>': ['D', 3, "key_d", 'd'],
    '<strong class="ggeut">ㅁ</strong>': ['W', 4, "key_w", 'w'],
    '<strong class="ggeut">ㅂ</strong>': ['Z', 5, "key_z", 'z'],
    '<strong class="ggeut">ㅅ</strong>': ['C', 3, "key_c", 'c'],
    '<strong class="ggeut">ㅆ</strong>': ['A', 5, "key_a", 'a'],
    '<strong class="ggeut">ㅇ</strong>': ['E', 3, "key_e", 'e'],
    '<strong class="ggeut">ㅈ</strong>': ['R', 2, "key_r", 'r'],
    '<strong class="ggeut">ㅊ</strong>': ['V', 2, "key_v", 'v'],
    '<strong class="ggeut">ㅋ</strong>': ['B', 2, "key_b", 'b'],
    '<strong class="ggeut">ㅌ</strong>': ['F', 2, "key_f", 'f'],
    '<strong class="ggeut">ㅍ</strong>': ['T', 2, "key_t", 't'],
    '<strong class="ggeut">ㅎ</strong>': ['Q', 5, "key_q", 'q'],
  };

  var K3_3shin_M = {
    '<strong class="cheot">ㄱ</strong>':  ['k', 8, "key_k"],
    '<strong class="cheot">ㄴ</strong>':  ['h', 7, "key_h"],
    '<strong class="cheot">ㄷ</strong>':  ['u', 7, "key_u"],
    '<strong class="cheot">ㄹ</strong>':  ['y', 7, "key_y"],
    '<strong class="cheot">ㅁ</strong>':  ['i', 8, "key_i"],
    '<strong class="cheot">ㅂ</strong>':  [';', 10, "key_semicolon"],
    '<strong class="cheot">ㅅ</strong>':  ['n', 7, "key_n"],
    '<strong class="cheot">ㅇ</strong>':  ['j', 7, "key_j"],
    '<strong class="cheot">ㅈ</strong>':  ['l', 9, "key_l"],
    '<strong class="cheot">ㅊ</strong>':  ['o', 9, "key_o"],
    '<strong class="cheot">ㅋ</strong>':  ['/', 10, "key_forwardslash"],
    '<strong class="cheot">ㅌ</strong>':  ['\'', 10, "key_apostrophe"],
    '<strong class="cheot">ㅍ</strong>':  ['p', 10, "key_p"],
    '<strong class="cheot">ㅎ</strong>':  ['m', 8, "key_m"],
    '<strong class="gawit">ㅏ</strong>': ['f', 2, "key_f"],
    '<strong class="gawit">ㅐ</strong>': ['r', 2, "key_r"],
    '<strong class="gawit">ㅒ</strong>': ['q', 5, "key_q"],
    '<strong class="gawit">ㅑ</strong>': ['w', 4, "key_w"],
    '<strong class="gawit">ㅓ</strong>': ['t', 2, "key_t"],
    '<strong class="gawit">ㅔ</strong>': ['c', 3, "key_c"],
    '<strong class="gawit">ㅖ</strong>': ['z', 5, "key_z"],
    '<strong class="gawit">ㅕ</strong>': ['e', 3, "key_e"],
    '<strong class="gawit">ㅗ</strong>': ['v', 2, "key_v"],
    '<strong class="gawit">ㅛ</strong>': ['x', 4, "key_x"],
    '<strong class="gawit">ㅜ</strong>': ['b', 2, "key_b"],
    '<strong class="gawit">ㅠ</strong>': ['a', 5, "key_a"],
    '<strong class="gawit">ㅡ</strong>': ['g', 2, "key_g"],
    '<strong class="gawit">ㅣ</strong>': ['d', 3, "key_d"],
    '<strong class="gawit">ㅢ</strong>': ['s', 4, "key_s"],
    '<strong class="gawit_right">ㅗ(↗)</strong>': ['P', 10, "key_p", 'p'],
    '<strong class="gawit_right">ㅗ(↘)</strong>': ['/', 10, "key_forwardslash", '?'],
    '<strong class="gawit_right">ㅜ(↗)</strong>': ['O', 9, "key_o", 'o'],
    '<strong class="ggeut">ㄱ</strong>': ['X', 4, "key_x", 'x'],
    '<strong class="ggeut">ㄴ</strong>': ['S', 4, "key_s", 's'],
    '<strong class="ggeut">ㄷ</strong>': ['G', 2, "key_g", 'g'],
    '<strong class="ggeut">ㄹ</strong>': ['W', 4, "key_w", 'w'],
    '<strong class="ggeut">ㅁ</strong>': ['Z', 5, "key_z", 'z'],
    '<strong class="ggeut">ㅂ</strong>': ['E', 3, "key_e", 'e'],
    '<strong class="ggeut">ㅅ</strong>': ['Q', 5, "key_q", 'q'],
    '<strong class="ggeut">ㅆ</strong>': ['D', 3, "key_d", 'd'],
    '<strong class="ggeut">ㅇ</strong>': ['A', 5, "key_a", 'a'],
    '<strong class="ggeut">ㅈ</strong>': ['R', 2, "key_r", 'r'],
    '<strong class="ggeut">ㅊ</strong>': ['B', 2, "key_b", 'b'],
    '<strong class="ggeut">ㅋ</strong>': ['T', 2, "key_t", 't'],
    '<strong class="ggeut">ㅌ</strong>': ['F', 2, "key_f", 'f'],
    '<strong class="ggeut">ㅍ</strong>': ['V', 2, "key_v", 'v'],
    '<strong class="ggeut">ㅎ</strong>': ['C', 3, "key_c", 'c'],
  };

  var K3_3shin_p1 = {
    '<strong class="cheot">ㄱ</strong>':  ['k', 8, "key_k"],
    '<strong class="cheot">ㄴ</strong>':  ['h', 7, "key_h"],
    '<strong class="cheot">ㄷ</strong>':  ['u', 7, "key_u"],
    '<strong class="cheot">ㄹ</strong>':  ['y', 7, "key_y"],
    '<strong class="cheot">ㅁ</strong>':  ['i', 8, "key_i"],
    '<strong class="cheot">ㅂ</strong>':  [';', 10, "key_semicolon"],
    '<strong class="cheot">ㅅ</strong>':  ['n', 7, "key_n"],
    '<strong class="cheot">ㅇ</strong>':  ['j', 7, "key_j"],
    '<strong class="cheot">ㅈ</strong>':  ['l', 9, "key_l"],
    '<strong class="cheot">ㅊ</strong>':  ['o', 9, "key_o"],
    '<strong class="cheot">ㅋ</strong>':  ['/', 10, "key_forwardslash"],
    '<strong class="cheot">ㅌ</strong>':  ['\'', 10, "key_apostrophe"],
    '<strong class="cheot">ㅍ</strong>':  ['p', 10, "key_p"],
    '<strong class="cheot">ㅎ</strong>':  ['m', 7, "key_m"],
    '<strong class="gawit">ㅏ</strong>': ['F', 2, "key_f", 'f'],
    '<strong class="gawit">ㅐ</strong>': ['T', 2, "key_t", 't'],
    '<strong class="gawit">ㅒ</strong>': ['Q', 5, "key_q", 'q'],
    '<strong class="gawit">ㅑ</strong>': ['W', 4, "key_w", 'w'],
    '<strong class="gawit">ㅓ</strong>': ['R', 2, "key_r", 'r'],
    '<strong class="gawit">ㅔ</strong>': ['C', 3, "key_c", 'c'],
    '<strong class="gawit">ㅖ</strong>': ['S', 4, "key_s", 's'],
    '<strong class="gawit">ㅕ</strong>': ['E', 3, "key_e", 'e'],
    '<strong class="gawit">ㅗ</strong>': ['V', 2, "key_v", 'v'],
    '<strong class="gawit">ㅛ</strong>': ['X', 4, "key_x", 'x'],
    '<strong class="gawit">ㅜ</strong>': ['B', 2, "key_b", 'b'],
    '<strong class="gawit">ㅠ</strong>': ['A', 5, "key_a", 'a'],
    '<strong class="gawit">ㅡ</strong>': ['G', 2, "key_g", 'g'],
    '<strong class="gawit">ㅣ</strong>': ['D', 3, "key_d", 'd'],
    '<strong class="gawit">ㅡ(↗)</strong>': ['I', 8, "key_i", 'i'],
    '<strong class="gawit">ㆍ(아래아)</strong>': ['Z', 5, "key_z", 'z'],
    '<strong class="gawit_right">ㆍ(아래아)(↗)</strong>': ['P', 10, "key_p", 'p'],
    '<strong class="gawit_right">ㅗ(↘)</strong>': ['/', 10, "key_forwardslash", '?'],
    '<strong class="gawit_right">ㅜ(↗)</strong>': ['O', 9, "key_o", 'o'],
    '<strong class="ggeut">ㄱ</strong>': ['c', 3, "key_c"],
    '<strong class="ggeut">ㄴ</strong>': ['s', 4, "key_s"],
    '<strong class="ggeut">ㄷ</strong>': ['g', 2, "key_g"],
    '<strong class="ggeut">ㄹ</strong>': ['w', 4, "key_w"],
    '<strong class="ggeut">ㅁ</strong>': ['z', 5, "key_z"],
    '<strong class="ggeut">ㅂ</strong>': ['e', 3, "key_e"],
    '<strong class="ggeut">ㅅ</strong>': ['q', 5, "key_q"],
    '<strong class="ggeut">ㅆ</strong>': ['x', 4, "key_x"],
    '<strong class="ggeut">ㅇ</strong>': ['a', 5, "key_a"],
    '<strong class="ggeut">ㅈ</strong>': ['v', 2, "key_v"],
    '<strong class="ggeut">ㅊ</strong>': ['t', 2, "key_t"],
    '<strong class="ggeut">ㅎ</strong>': ['d', 3, "key_d"],
    '<strong class="ggeut">ㅌ</strong>': ['r', 2, "key_r"],
    '<strong class="ggeut">ㅋ</strong>': ['b', 2, "key_b"],
    '<strong class="ggeut">ㅍ</strong>': ['f', 2, "key_f"],
  };

  var K3_3moa_semoe_2015 = {
    // 배열의 안의 값이 배열일 때
    // 첫째 배열은 unicode 오름차순으로 넣고 나머지는 첫째에 맞추어서 넣는다
    '<strong class="cheot">ㄱ</strong>':  ['k', 8, "key_k"],
    '<strong class="cheot">ㄲ [ㄱ , ㅇ]</strong>':  [['j','k'], [7,8], ["key_j","key_k"]],
    '<strong class="cheot">ㄴ</strong>':  ['u', 7, "key_u"],
    '<strong class="cheot">ㄷ</strong>':  ['i', 8, "key_i"],
    '<strong class="cheot">ㄸ [ㄷ , ㅇ]</strong>':  [['i','j'], [7,8], ["key_i","key_j"]],
    '<strong class="cheot">ㄹ</strong>':  ['m', [7,8], ["key_m","key_m"]],
    '<strong class="cheot">ㅁ</strong>':  ['y', 7, "key_y"],
    '<strong class="cheot">ㅂ</strong>':  ['o', 9, "key_o"],
    '<strong class="cheot">ㅃ [ㅂ , ㅇ]</strong>':  [['j','o'], [7,9], ["key_j","key_o"]],
    '<strong class="cheot">ㅅ</strong>':  ['h', 7, "key_h"],
    '<strong class="cheot">ㅆ [ㅅ , ㅇ]</strong>':  [['h','j'], [7,8], ["key_h","key_j"]],
    '<strong class="cheot">ㅇ</strong>':  ['j', 7, "key_j"],
    '<strong class="cheot">ㅈ</strong>':  ['l', 9, "key_l"],
    '<strong class="cheot">ㅉ [ㅈ , ㅇ]</strong>':  [['j','l'], [7,9], ["key_j","key_l"]],
    '<strong class="cheot">ㅊ [ㅈ , ㅎ]</strong>':  [['l','n'], [9,7], ["key_l","key_n"]],
    '<strong class="cheot">ㅋ [ㄱ , ㅎ]</strong>':  [['k','n'], [8,7], ["key_k","key_n"]],
    '<strong class="cheot">ㅌ [ㄷ , ㅎ]</strong>':  [['i','n'], [7,8], ["key_i","key_n"]],
    '<strong class="cheot">ㅍ [ㅂ , ㅎ]</strong>':  [['n','o'], [7,9], ["key_n","key_o"]],
    '<strong class="cheot">ㅎ</strong>':  ['n', 7, "key_n"],
    '<strong class="gawit">ㅏ</strong>': ['f', 2, "key_f"],
    //'<strong class="gawit">ㅐ</strong>': ['t', 2, "key_t"],fd
    '<strong class="gawit">ㅐ [ㅏ , ㅣ]</strong>': [['d','f'], [3,2], ["key_d","key_f"]],
    '<strong class="gawit">ㅒ [모음⇧ , ㅕ]</strong>': [['p','t'], [10,2], ["key_p","key_t"]],
    '<strong class="gawit">ㅑ [모음⇧ , ㅓ]</strong>': [['p','r'], [10,2], ["key_p","key_r"]],
    '<strong class="gawit">ㅓ</strong>': ['r', 2, "key_r"],
    '<strong class="gawit">ㅔ</strong>': ['c', [2,3], ["key_c","key_c"]],
    '<strong class="gawit">ㅕ</strong>': ['t', 2, "key_t"],
    '<strong class="gawit">ㅖ [모음⇧ , ㅔ]</strong>': [['c','v'], [3,2], ["key_c","key_v"]],
    '<strong class="gawit">ㅗ</strong>': ['v', 2, "key_v"],
    '<strong class="gawit">ㅘ [ㅗ , ㅏ]</strong>': [['f','p'], [2,10], ["key_f","key_p"]],
    '<strong class="gawit">ㅙ [ㅗ , ㅏ , ㅣ]</strong': [['d', 'f', 'p'], [2,3,10], ["key_d","key_f","key_p"]],
    //'<strong class="gawit">ㅙ[ㅏ,ㅚ]</strong>': [['f','v'], [2,2], ["key_f","key_v"]],
    //'<strong class="gawit">ㅙ[ㅐ,ㅗ]</strong>': [['f','v'], [2,2], ["key_f","key_v"]],
    //'<strong class="gawit">ㅙ[ㅘ,ㅣ]</strong>': [['f','v'], [2,2], ["key_f","key_v"]],
    '<strong class="gawit">ㅚ [ㅗ , ㅣ]</strong>': [['d','v'], [3,2], ["key_d","key_v"]],
    '<strong class="gawit">ㅛ [모음⇧, ㅗ]</strong>': [['p','v'], [10,2], ["key_p","key_v"]],
    '<strong class="gawit">ㅛ [ㅏ , ㅓ]</strong>': [['f','r'], [2,3], ["key_f","key_r"]],
    '<strong class="gawit">ㅜ</strong>': ['b', 2, "key_b"],
    '<strong class="gawit">ㅝ [ㅜ , ㅓ]</strong>': [['\'','r'], [10,2], ["key_apostrophe","key_r"]],
    //'<strong class="gawit">ㅞ[ㅓ,ㅟ]</strong>': [['b','r'], [2,2], ["key_b","key_r"]],
    '<strong class="gawit">ㅞ [ㅜ , ㅔ]</strong>': [['\'','c'], [10,3,2], ["key_apostrophe","key_c","key_c"]],
    //'<strong class="gawit">ㅞ[ㅝ,ㅣ]</strong>': [['b','c'], [2,3], ["key_b","key_c"]],
    '<strong class="gawit">ㅟ [ㅜ , ㅣ]</strong>': [['\'','d'], [10,3], ["key_apostrophe","key_d"]],
    '<strong class="gawit">ㅠ [ㅜ , 모음⇧]</strong>': [['b','v'], [2,3], ["key_b","key_v"]],
    '<strong class="gawit">ㅡ</strong>': ['g', 2, "key_g"],
    '<strong class="gawit">ㅢ [ㅡ , ㅣ]</strong>': [['d','g'], [3,2], ["key_d","key_g"]],
    '<strong class="gawit">ㅣ</strong>': ['d', 3, "key_d"],
    //'<strong class="gawit">ᅟᆞᅟᆢ[ㆍ,ㆍ]</strong>': ['d', 3, "key_d"],
    '<strong class="gawit_right">ㅗ(↗)</strong>': ['p', 10, "key_p"],
    '<strong class="gawit_right">ㅜ(↗)</strong>': ['\'', 10, "key_apostrophe"],
    '<strong class="ggeut">ㄱ</strong>': ['x', 4, "key_x"],
    '<strong class="ggeut">ㄲ [ㄱ , ㅇ]</strong>': [['a','x'], [5,4], ["key_a","key_x"]],
    '<strong class="ggeut">ㄳ [ㄱ , ㅅ]</strong>': [['q','x'], [5,1], ["key_q","key_x"]],
    '<strong class="ggeut">ㄴ</strong>': ['s', 4, "key_s"],
    '<strong class="ggeut">ㄵ [ㄴ , ㅈ]</strong>': [['e','s'], [3,4], ["key_e","key_s"]],
    // 한 글쇠를 두 번 누르는 것은 되지 않으니 한 번에 넘긴다
    //'<strong class="ggeut">ㄶ[ㄴ,ㄴ]</strong>': [['s'], [4], ["key_s"]],
    '<strong class="ggeut">ㄶ [ㄴ , ㅀ]</strong>': [['a','s'], [5,4], ["key_a","key_s"]],
    //'<strong class="ggeut">ㄶ[ㄴ,ㅎ]</strong>': [['a','s'], [5,4], ["key_a","key_s"]],
    '<strong class="ggeut">ㄷ [ㅁ , 종성⇧]</strong>': [[';','z'], [10,5], ["key_semicolon","key_z"]],
    '<strong class="ggeut">ㄹ</strong>': ['e', 3, "key_e"],
    '<strong class="ggeut">ㄺ [ㄹ , ㄱ]</strong>': [['e','x'], [3,1], ["key_e","key_x"]],
    '<strong class="ggeut">ㄺ [ㅁ , ㄱ]</strong>': [['x','z'], [4,5], ["key_x","key_z"]],
    '<strong class="ggeut">ㄻ [ㄹ , ㅁ]</strong>': [['e','z'], [3,5], ["key_e","key_z"]],
    '<strong class="ggeut">ㄼ [ㄹ , ㅂ]</strong>': [['e','w'], [3,4], ["key_e","key_w"]],
    '<strong class="ggeut">ㄽ [ㄹ , ㅅ]</strong>': [['e','q'], [3,5], ["key_e","key_q"]],
    '<strong class="ggeut">ㄾ [ㅀ , ㄷ]</strong>': [['a','z'], [5,4], ["key_a","key_z"]],
    '<strong class="ggeut">ㄿ [ㅀ , ㅂ]</strong>': [['a','w'], [5,4], ["key_a","key_w"]],
    '<strong class="ggeut">ㅀ [ㅇ , 종성⇧]</strong>': [[';','a'], [10,5], ["key_semicolon","key_a"]],
    '<strong class="ggeut">ㅁ</strong>': ['z', 5, "key_z"],
    '<strong class="ggeut">ㅂ</strong>': ['w', 4, "key_w"],
    '<strong class="ggeut">ㅄ [ㅂ , ㅅ]</strong>': [['q','w'], [5,4], ["key_q","key_w"]],
    '<strong class="ggeut">ㅅ</strong>': ['q', 5, "key_q"],
    '<strong class="ggeut">ㅆ</strong>': [';', 10, "key_semicolon"],
    //'<strong class="ggeut">ㅆ[ㅅ,ㅇ]</strong>': [['a','q'], [5,5], ["key_a","key_q"]],
    '<strong class="ggeut">ㅇ</strong>': ['a', 5, "key_a"],
    '<strong class="ggeut">ㅈ [ㄹ , 종성⇧]</strong>': [[';','e'], [10,3], ["key_semicolon","key_e"]],
    '<strong class="ggeut">ㅊ [ㅅ , 종성⇧]</strong>': [[';','q'], [10,5], ["key_semicolon","key_q"]],
    '<strong class="ggeut">ㅎ [ㄴ , 종성⇧]</strong>': [[';','s'], [10,4], ["key_semicolon","key_s"]],
    '<strong class="ggeut">ㅌ [ㅎ , ㄷ]</strong>': [['s','z'], [4,5], ["key_s","key_z"]],
    //'<strong class="ggeut">ㅌ[ㄷ,ㅎ]</strong>': [['s','z'], [4,5], ["key_s","key_z"]],
    '<strong class="ggeut">ㅋ [ㄱ , 종성⇧]</strong>': [[';','x'], [10,4], ["key_semicolon","key_x"]],
    //'<strong class="ggeut">ㅋ[ㄱ,ㅎ]</strong>': [[';','x'], [10,4], ["key_semicolon","key_x"]],
    '<strong class="ggeut">ㅍ [ㅂ , 종성⇧]</strong>': [[';','w'], [10,4], ["key_semicolon","key_w"]],
    //'<strong class="ggeut">ㅍ[ㅂ,ㅎ]</strong>': [[';','w'], [10,4], ["key_semicolon","key_w"]],
  };

  var K3_3moa_semoe_2016 = {
    // 배열의 안의 값이 배열일 때
    // 첫째 배열은 unicode 오름차순으로 넣고 나머지는 첫째에 맞추어서 넣는다
    '<strong class="cheot">ㄱ</strong>':  ['k', 8, "key_k"],
    '<strong class="cheot">ㄲ [ㄱ , ㅇ]</strong>':  [['j','k'], [7,8], ["key_j","key_k"]],
    '<strong class="cheot">ㄴ</strong>':  ['u', 7, "key_u"],
    '<strong class="cheot">ㄷ</strong>':  ['i', 8, "key_i"],
    '<strong class="cheot">ㄸ [ㄷ , ㅇ]</strong>':  [['i','j'], [7,8], ["key_i","key_j"]],
    '<strong class="cheot">ㄹ</strong>':  ['m', [7,8], ["key_m","key_m"]],
    '<strong class="cheot">ㅁ</strong>':  ['y', 7, "key_y"],
    '<strong class="cheot">ㅂ</strong>':  ['o', 9, "key_o"],
    '<strong class="cheot">ㅃ [ㅂ , ㅇ]</strong>':  [['j','o'], [7,9], ["key_j","key_o"]],
    '<strong class="cheot">ㅅ</strong>':  ['n', 7, "key_n"],
    '<strong class="cheot">ㅆ [ㅅ , ㅇ]</strong>':  [['j','n'], [8,7], ["key_j","key_n"]],
    '<strong class="cheot">ㅇ</strong>':  ['j', 7, "key_j"],
    '<strong class="cheot">ㅈ</strong>':  ['l', 9, "key_l"],
    '<strong class="cheot">ㅉ [ㅈ , ㅇ]</strong>':  [['j','l'], [7,9], ["key_j","key_l"]],
    '<strong class="cheot">ㅊ [ㅈ , ㅎ]</strong>':  [['h','l'], [7,9], ["key_h","key_l"]],
    '<strong class="cheot">ㅋ [ㄱ , ㅎ]</strong>':  [['h','k'], [7,8], ["key_h","key_k"]],
	'<strong class="cheot">ㅌ [ㄷ , ㅎ]</strong>':  [['h','i'], [7,8], ["key_h","key_i"]],
    '<strong class="cheot">ㅍ [ㅂ , ㅎ]</strong>':  [['h','o'], [7,9], ["key_h","key_o"]],
    '<strong class="cheot">ㅎ</strong>':  ['h', 7, "key_h"],
    '<strong class="gawit">ㅏ</strong>': ['f', 2, "key_f"],
    //'<strong class="gawit">ㅐ</strong>': ['t', 2, "key_t"],fd
    '<strong class="gawit">ㅐ [ㅏ , ㅣ]</strong>': [['d','f'], [3,2], ["key_d","key_f"]],
    '<strong class="gawit">ㅒ [모음⇧ , ㅕ]</strong>': [['[','t'], [10,2], ["key_left_bracket","key_t"]],
    '<strong class="gawit">ㅑ [모음⇧ , ㅓ]</strong>': [['[','r'], [10,2], ["key_left_bracket","key_r"]],
    '<strong class="gawit">ㅓ</strong>': ['r', 2, "key_r"],
    '<strong class="gawit">ㅔ</strong>': ['c', [2,3], ["key_c","key_c"]],
    '<strong class="gawit">ㅕ</strong>': ['t', 2, "key_t"],
    '<strong class="gawit">ㅖ [모음⇧ , ㅔ]</strong>': [['c','v'], [3,2], ["key_c","key_v"]],
    '<strong class="gawit">ㅗ</strong>': ['v', 2, "key_v"],
    '<strong class="gawit">ㅘ [ㅗ , ㅏ]</strong>': [['[','f'], [10,2], ["key_left_bracket","key_f"]],
	'<strong class="gawit">ㅙ [ㅗ , ㅏ , ㅣ]</strong': [['[','d','f'], [10,2,3], ["key_left_bracket","key_d","key_f"]],
    //'<strong class="gawit">ㅙ[ㅏ,ㅚ]</strong>': [['f','v'], [2,2], ["key_f","key_v"]],
    //'<strong class="gawit">ㅙ[ㅐ,ㅗ]</strong>': [['f','v'], [2,2], ["key_f","key_v"]],
    //'<strong class="gawit">ㅙ[ㅘ,ㅣ]</strong>': [['f','v'], [2,2], ["key_f","key_v"]],
    '<strong class="gawit">ㅚ [ㅗ , ㅣ]</strong>': [['d','v'], [3,2], ["key_d","key_v"]],
    '<strong class="gawit">ㅛ [모음⇧, ㅗ]</strong>': [['[','v'], [10,2], ["key_left_bracket","key_v"]],
    '<strong class="gawit">ㅛ [ㅏ , ㅓ]</strong>': [['f','r'], [2,3], ["key_f","key_r"]],
    '<strong class="gawit">ㅜ</strong>': ['b', 2, "key_b"],
    '<strong class="gawit">ㅝ [ㅜ , ㅓ]</strong>': [['p','r'], [10,2], ["key_p","key_r"]],
    //'<strong class="gawit">ㅞ[ㅓ,ㅟ]</strong>': [['b','r'], [2,2], ["key_b","key_r"]],
    '<strong class="gawit">ㅞ [ㅜ , ㅔ]</strong>': [['c','p'], [2,3,10], ["key_c","key_c","key_p"]],
    //'<strong class="gawit">ㅞ[ㅝ,ㅣ]</strong>': [['b','c'], [2,3], ["key_b","key_c"]],
    '<strong class="gawit">ㅟ [ㅜ , ㅣ]</strong>': [['d','p'], [3,10], ["key_d","key_p"]],
    '<strong class="gawit">ㅠ [ㅜ , 모음⇧]</strong>': [['b','v'], [2,3], ["key_b","key_v"]],
    '<strong class="gawit">ㅡ</strong>': ['g', 2, "key_g"],
    '<strong class="gawit">ㅢ [ㅡ , ㅣ]</strong>': [['d','g'], [3,2], ["key_d","key_g"]],
    '<strong class="gawit">ㅣ</strong>': ['d', 3, "key_d"],
    //'<strong class="gawit">ᅟᆞᅟᆢ[ㆍ,ㆍ]</strong>': ['d', 3, "key_d"],
    '<strong class="gawit_right">ㅗ(↗)</strong>': ['[', 10, "key_left_bracket"],
    '<strong class="gawit_right">ㅜ(↗)</strong>': ['p', 10, "key_p"],
    '<strong class="ggeut">ㄱ</strong>': ['x', 4, "key_x"],
    '<strong class="ggeut">ㄲ [ㄱ , ㅇ]</strong>': [['a','x'], [5,4], ["key_a","key_x"]],
    '<strong class="ggeut">ㄳ [ㄱ , ㅅ]</strong>': [['q','x'], [5,1], ["key_q","key_x"]],
    '<strong class="ggeut">ㄴ</strong>': ['s', 4, "key_s"],
    '<strong class="ggeut">ㄵ [ㄴ , ㅈ]</strong>': [['e','s'], [3,4], ["key_e","key_s"]],
    // 한 글쇠를 두 번 누르는 것은 되지 않으니 한 번에 넘긴다
    //'<strong class="ggeut">ㄶ[ㄴ,ㄴ]</strong>': [['s'], [4], ["key_s"]],
    '<strong class="ggeut">ㄶ [ㄴ , ㅀ]</strong>': [['a','s'], [5,4], ["key_a","key_s"]],
    //'<strong class="ggeut">ㄶ[ㄴ,ㅎ]</strong>': [['a','s'], [5,4], ["key_a","key_s"]],
    '<strong class="ggeut">ㄷ [ㅁ , 종성⇧]</strong>': [[';','z'], [10,5], ["key_semicolon","key_z"]],
    '<strong class="ggeut">ㄹ</strong>': ['e', 3, "key_e"],
    '<strong class="ggeut">ㄺ [ㄹ , ㄱ]</strong>': [['e','x'], [3,1], ["key_e","key_x"]],
    '<strong class="ggeut">ㄺ [ㅁ , ㄱ]</strong>': [['x','z'], [4,5], ["key_x","key_z"]],
    '<strong class="ggeut">ㄻ [ㄹ , ㅁ]</strong>': [['e','z'], [3,5], ["key_e","key_z"]],
    '<strong class="ggeut">ㄼ [ㄹ , ㅂ]</strong>': [['e','w'], [3,4], ["key_e","key_w"]],
    '<strong class="ggeut">ㄽ [ㄹ , ㅅ]</strong>': [['e','q'], [3,5], ["key_e","key_q"]],
    '<strong class="ggeut">ㄾ [ㅀ , ㄷ]</strong>': [['a','z'], [5,4], ["key_a","key_z"]],
    '<strong class="ggeut">ㄿ [ㅀ , ㅂ]</strong>': [['a','w'], [5,4], ["key_a","key_w"]],
    '<strong class="ggeut">ㅀ [ㅇ , 종성⇧]</strong>': [[';','a'], [10,5], ["key_semicolon","key_a"]],
    '<strong class="ggeut">ㅁ</strong>': ['z', 5, "key_z"],
    '<strong class="ggeut">ㅂ</strong>': ['w', 4, "key_w"],
    '<strong class="ggeut">ㅄ [ㅂ , ㅅ]</strong>': [['q','w'], [5,4], ["key_q","key_w"]],
    '<strong class="ggeut">ㅅ</strong>': ['q', 5, "key_q"],
    '<strong class="ggeut">ㅆ</strong>': [';', 10, "key_semicolon"],
    //'<strong class="ggeut">ㅆ[ㅅ,ㅇ]</strong>': [['a','q'], [5,5], ["key_a","key_q"]],
    '<strong class="ggeut">ㅇ</strong>': ['a', 5, "key_a"],
    '<strong class="ggeut">ㅈ [ㄹ , 종성⇧]</strong>': [[';','e'], [10,3], ["key_semicolon","key_e"]],
    '<strong class="ggeut">ㅊ [ㅅ , 종성⇧]</strong>': [[';','q'], [10,5], ["key_semicolon","key_q"]],
    '<strong class="ggeut">ㅎ [ㄴ , 종성⇧]</strong>': [[';','s'], [10,4], ["key_semicolon","key_s"]],
    '<strong class="ggeut">ㅌ [ㅎ , ㄷ]</strong>': [['s','z'], [4,5], ["key_s","key_z"]],
    //'<strong class="ggeut">ㅌ[ㄷ,ㅎ]</strong>': [['s','z'], [4,5], ["key_s","key_z"]],
    '<strong class="ggeut">ㅋ [ㄱ , 종성⇧]</strong>': [[';','x'], [10,4], ["key_semicolon","key_x"]],
    //'<strong class="ggeut">ㅋ[ㄱ,ㅎ]</strong>': [[';','x'], [10,4], ["key_semicolon","key_x"]],
    '<strong class="ggeut">ㅍ [ㅂ , 종성⇧]</strong>': [[';','w'], [10,4], ["key_semicolon","key_w"]],
    //'<strong class="ggeut">ㅍ[ㅂ,ㅎ]</strong>': [[';','w'], [10,4], ["key_semicolon","key_w"]],
  };

  // object
  switch (true) {
    case /3-90/.test(KO_type) :
      return K3_3_90;
    case /3-91/.test(KO_type) :
      return K3_3_91;
    case /3-93/.test(KO_type) :
      return {};
    case /3-2015p/.test(KO_type) :
      return K3_3_2015_patal;
    case /3-2015/.test(KO_type) :
      return K3_3_2015;
    case /3-2012/.test(KO_type) :
      return K3_3_2012;
    case /3moa-semoe-2015/.test(KO_type) :
      return K3_3moa_semoe_2015;
    case /3moa-semoe-2016/.test(KO_type) :
      return K3_3moa_semoe_2016;
    case /3moa/.test(KO_type) :
      return {};
    case /3sun/.test(KO_type) :
      return {};
    case /3shin-1995/.test(KO_type) :
      return K3_3shin_1995;
    case /3shin-2003/.test(KO_type) :
      return K3_3shin_2003;
    case /3shin-2012/.test(KO_type) :
      return K3_3shin_2012;
    case /3shin-2015/.test(KO_type) :
      return K3_3shin_2015;
    case /3shin-m/.test(KO_type) :
      return K3_3shin_M;
    case /3shin-p1/.test(KO_type) :
      return K3_3shin_p1;
    case /2-ksx5002/.test(KO_type) :
      return K2_2_ksx5002;
    case /2sun-ksx5002/.test(KO_type) :
      return K2_2sun_ksx5002;
    case /2-kps9256/.test(KO_type) :
      return K2_2_kps9256;
    default :
      return {};
  }

}
